algoritmo "IDADE PARA DIRIGIR"
var
     ano, nasceu: real
inicio
          Escreval ("Em que ano nós estamos?")
          Leia (ano)
          Escreval ("Em que ano você nasceu?")
          Leia (nasceu)
          Se ano - nasceu > 18 entao
          Escreval ("Você está apto para tirar a CHN")
          Senao
          Escreval ("Você não está apto para tirar a CHN")
          FimSe
fimalgoritmo

Feito por @brunoMBS
19/02/2022