algoritmo "Idade até o final do ano"
var
                ano_atual: inteiro
                ano_nascimento, idade: inteiro
inicio
      Escreva ("Em que ano nós estamos? ")
      Leia (ano_atual)
      Escreva ("Em que ano eu nasci? ")
      Leia (ano_nascimento)
      idade <- ano_atual - ano_nascimento
      Escreva ("Minha idade é ou será " ,idade , " até o fim do ano")
fimalgoritmo

Feito por @brunoMBS
10/02/2022